package com.colarsort.app.data.repository

import com.colarsort.app.data.db.dao.OrderDao
import com.colarsort.app.data.entities.Orders

class OrdersRepo(dao : OrderDao) : BaseRepo<Orders, OrderDao>(dao)
{

    suspend fun getDataById(id : Int) : Orders = dao.getDataById(id)

    suspend fun getAll() : List<Orders> = dao.getAllData()

    /**
     * Inserts a model into the database and returns the auto-generated row ID.
     *
     * This behaves like the regular `insert()` function but additionally returns
     * the primary key value generated by SQLite after a successful insert.
     *
     * @param model The data model that stores the value.
     * @return The ID of the newly inserted row, or -1 if the insert failed.
     */
    suspend fun insertAndReturnId(model: Orders): Long =
        dao.insertAndGetId(order = model)

}