package com.colarsort.app.repository

import android.content.ContentValues
import android.database.Cursor
import com.colarsort.app.database.DatabaseHelper
import com.colarsort.app.database.OrdersTable
import com.colarsort.app.models.Orders
import com.colarsort.app.models.RowConversion

class OrdersRepo(dbHelper: DatabaseHelper) : CRUDRepo<Orders>(dbHelper)
{
    override val tableName: String = OrdersTable.TABLE_NAME
    override val tableRows: Array<String> = arrayOf(
        OrdersTable.ID,
        OrdersTable.CUSTOMER_NAME,
        OrdersTable.STATUS,
        OrdersTable.EXPECTED_DELIVERY
    )

    override fun converter(cursor: Cursor): Orders {
        return Orders(
            id = cursor.getInt(cursor.getColumnIndexOrThrow(OrdersTable.ID)),
            customerName = cursor.getString(cursor.getColumnIndexOrThrow(OrdersTable.CUSTOMER_NAME)),
            status = cursor.getString(cursor.getColumnIndexOrThrow(OrdersTable.STATUS)),
            expectedDelivery = cursor.getString(cursor.getColumnIndexOrThrow(OrdersTable.EXPECTED_DELIVERY))
        )
    }

    fun getRow(id : Int) : Orders?
    {
        val db = dbHelper.readableDatabase

        val cursor = db.rawQuery(
            "SELECT * FROM $tableName WHERE ${OrdersTable.ID} = ?",
            arrayOf(id.toString())
        )
        cursor.use {
            if(it.moveToNext())
            {
                return Orders(
                    id = it.getInt(it.getColumnIndexOrThrow(OrdersTable.ID)),
                    customerName = it.getString(it.getColumnIndexOrThrow(OrdersTable.CUSTOMER_NAME)),
                    status = it.getString(it.getColumnIndexOrThrow(OrdersTable.STATUS)),
                    expectedDelivery = it.getString(it.getColumnIndexOrThrow(OrdersTable.EXPECTED_DELIVERY))
                )
            }
        }

        return null
    }

    /**
     * Inserts a model into the database and returns the auto-generated row ID.
     *
     * This behaves like the regular `insert()` function but additionally returns
     * the primary key value generated by SQLite after a successful insert.
     *
     * @param model The data model implementing [RowConversion] to be saved.
     * @return The ID of the newly inserted row, or -1 if the insert failed.
     */
    fun insertAndReturnId(model: RowConversion): Long {
        val db = dbHelper.writableDatabase

        val values = model.toRow()
        val cv = ContentValues()

        putValue(cv, OrdersTable.ID, values[0])
        putValue(cv, OrdersTable.CUSTOMER_NAME, values[1])
        putValue(cv, OrdersTable.STATUS, values[2])
        putValue(cv, OrdersTable.EXPECTED_DELIVERY, values[3])

        val id = db.insert(tableName, null, cv)
        db.close()

        return id
    }
}